name: Release oras-project/registry container image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_USER_TOKEN }}