name: oras-alpha

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .prerelease.goleaser.yml
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}